all:
  hosts:
    node1:
      ansible_host: 161.35.41.118
      ip: 10.106.0.2
      access_ip: 10.106.0.2
    node2:
      ansible_host: 161.35.41.224
      ip: 10.106.0.3
      access_ip: 10.106.0.3
    node3:
      ansible_host: 167.99.82.143
      ip: 10.106.0.4
      access_ip: 10.106.0.4
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
